# fly.toml app configuration file generated for arcade-auger-app-polished-grass-754 on 2025-08-01T06:11:19-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'arcade-auger-app-polished-grass-754'
primary_region = 'iad'

[build]
  dockerfile = './Dockerfile'

[deploy]
  release_command = 'bundle exec rails db:prepare'

[env]
  RAILS_ENV = 'production'

[[services]]
  protocol = 'tcp'
  internal_port = 3000 
  processes = ['app']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
